### PR TITLE
chore: allow ToolsDevelopment to Assume CI Role

### PR DESCRIPTION
**Pull request by texastony**
*Issue #, if available:* 

*Description of changes:*
Allow  ToolsDevelopment to Assume GitHub CI Role.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

# Check any applicable:
- [ ] Were any files moved? Moving files changes their URL, which breaks all hyperlinks to the files.

### CODE REVIEW

**Comment by texastony** [comment]
I did not intend for there to be a significant change to the CFN Template.
I believe my IDE reformatted it.

**Comment by texastony** [comment]
The S3EC-Java has transient CI Failures.
```
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 10.402 s <<< FAILURE! - in software.amazon.encryption.s3.examples.MultipartUploadExampleTest
Error:  testMultipartUploadExamples  Time elapsed: 10.402 s  <<< ERROR!
software.amazon.encryption.s3.S3EncryptionClientException: Exception while performing Multipart Upload PutObject
	at software.amazon.encryption.s3.examples.MultipartUploadExampleTest.testMultipartUploadExamples(MultipartUploadExampleTest.java:13)
Caused by: software.amazon.encryption.s3.S3EncryptionClientException: software.amazon.encryption.s3.S3EncryptionClientException: Re-subscription is not supported! Retry the entire operation.
	at software.amazon.encryption.s3.examples.MultipartUploadExampleTest.testMultipartUploadExamples(MultipartUploadExampleTest.java:13)
Caused by: java.util.concurrent.ExecutionException: software.amazon.encryption.s3.S3EncryptionClientException: Re-subscription is not supported! Retry the entire operation.
	at software.amazon.encryption.s3.examples.MultipartUploadExampleTest.testMultipartUploadExamples(MultipartUploadExampleTest.java:13)
Caused by: software.amazon.encryption.s3.S3EncryptionClientException: Re-subscription is not supported! Retry the entire operation.
Caused by: software.amazon.encryption.s3.S3EncryptionClientException: Re-subscription is not supported! Retry the entire operation.
```

Which is annoying and we should fix this, 
but this PR is not inducing these failures.

**Review by josecorella — APPROVED** [review]

**Review by justplaz — APPROVED** [review]
LGTM

**Comment by texastony** [comment]
Deployed this PR and confirmed on my local that I can access these resources via ToolsDevelopment.

**Pull request merged**
