### PR TITLE
fix: unwrap completion exception in AbortMultipartUpload and inside multipart putObject

### PR DESCRIPTION
**Pull request by justplaz**
*Issue #, if available:* https://github.com/aws/amazon-s3-encryption-client-java/issues/165

*Description of changes:* Unwraps completion exception thrown from `AbortMultipartUpload` in the default client, and in the `uploadPart` calls within "high-level" multipart `putObject`. 

The latter is not tested, because the API surface does not allow for (convenient) testing. 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

# Check any applicable:
- [ ] Were any files moved? Moving files changes their URL, which breaks all hyperlinks to the files.

### CODE REVIEW

**Comment by justplaz** [comment]
Passing CI in my fork: https://github.com/justplaz/amazon-s3-encryption-client-java/actions/runs/5394156397

**Comment by justplaz** [comment]
Passing CI in this repo: https://github.com/aws/amazon-s3-encryption-client-java/actions/runs/5395477614

**Review by imabhichow — APPROVED** [review]
lgtm!

**Comment by justplaz** [comment]
closing this PR, I will re-open directly from the repo, as CI just won't work when run from forks.

**Pull request closed without merging**
